[lint]
exclude = ["tests/testthat/*-lazy.R"]
extend-select = ["TESTTHAT"]

[lint.unused_function]
skipped-functions = ["^pl"]

[lint.duplicated_arguments]
extend-skipped-functions = ["translate_dots"]

[lint.missing_argument]
extend-skipped-functions = ["pl$DataFrame", "pl$LazyFrame"]