name: html-5-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  html-5-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: 'https://community.r-multiverse.org' 
        env:
          NOT_CRAN: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          upgrade: "TRUE"
          cache-version: 2
          extra-packages: |
            any::rcmdcheck
            any::V8
          dependencies: "character()"

      - name: Install pdflatex
        run: sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Install tidy
        run: sudo apt install tidy

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--as-cran", "--no-codoc", "--no-examples", "--no-tests", "--no-vignettes", "--no-build-vignettes", "--ignore-vignettes", "--no-install")'
          build_args: 'c("--no-build-vignettes")'
          error-on: '"note"'
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          _R_CHECK_CRAN_INCOMING_: false
          _R_CHECK_RD_XREFS_: false
